### ISSUE TITLE
Implement Clone for secret types

### ISSUE THREAD

**Issue by NEO97online** [ramosbugs/oauth2-rs#189] opened 2022-10-07 05:07 UTC
It seems like secret types like PkceCodeVerifier are simply wrapping a string; is there a reason they don't implement `Clone`?

If I need to clone my verifier, is it fine to simply grab the secret from the existing one and use it to create a new one? Like so:

```rs
fn clone_verifier(verifier: &PkceCodeVerifier) -> PkceCodeVerifier {
    PkceCodeVerifier::new(verifier.secret().clone())
} 

```

**Comment by ramosbugs** [comment] 2022-10-07 06:10
hey @auderer, it looks like I omitted `Clone` from this type in order to discourage accidental reuse of PKCE challenges across requests: https://github.com/ramosbugs/oauth2-rs/blob/5a66b83c681fc82ac2964e749868f21c34380528/src/types.rs#L412-L413

I'm not entirely opposed to revisiting this decision if the lack of `Clone` makes the API cumbersome for typical use cases, but the workaround you described should work.

**Comment by AnassKartit** [comment] 2022-10-27 14:36
@ramosbugs I am getting this error:
use of moved value: `verifier`
   --> examples/interop.rs:184:22
    |
127 |         let (pkce_code_challenge, verifier) = PkceCodeChallenge::new_random_sha256();
    |                                   -------- move occurs because `verifier` has type `PkceCodeVerifier`, which does not implement the `Copy` trait
...
184 |         .set_pkce_verifier(verifier)
    |                            ^^^^^^^^ value moved here, in previous iteration of loop

**Comment by ramosbugs** [comment] 2022-10-27 21:20
@AnassKartit it's hard to provide guidance with such limited information and no code example. in any case, the workaround described above should work, though I'm curious of why this would need to be used in a loop unless the same verifier is being used across multiple requests, which is the misuse case that omitting `Clone` was intended to help prevent.

**Comment by ramosbugs** [comment] 2023-11-26 03:03
Closing since this API was intentional and there is a straightforward workaround.

**Closed by ramosbugs** 2023-11-26 03:03 UTC

**Comment by anderspitman** [comment] 2024-06-26 14:46
Ran into this and came up with the same workaround. Only suggestion would be to maybe mention in the documentation for `PkceCodeVerifier` that `Clone` is intentionally missing.
