### ISSUE TITLE
unable to parse expires_in if it is a string

### ISSUE THREAD

**Issue by adrosa** [ramosbugs/oauth2-rs#151] opened 2021-07-02 20:33 UTC
https://login.microsoftonline.com/*/oauth2/token serializes expires_in as a string

this causes following error
```
Error: Failed to parse server response

Caused by:
    0: expires_in: invalid type: string "86399", expected u64 at line 1 column 43
    1: invalid type: string "86399", expected u64 at line 1 column 43
```
Can be fixed by following https://github.com/serde-rs/json/issues/317

**Comment by ramosbugs** [comment] 2021-07-02 20:50
duplicate of #85

**Closed by ramosbugs** 2021-07-02 20:50 UTC

**Comment by adrosa** [comment] 2021-07-02 21:42
sorry.
